services:
  roscore:
    build:
      context: images/ros_base
      dockerfile: Dockerfile
      target: ros_image
    network_mode: "host"
    volumes:
        - ${WORKSPACE_DIR}:/catkin_ws
        - ${ROS_LOG_DIR}:/roslog
    command: >
              bash -c "
              source /opt/ros/noetic/setup.bash 
              && export ROS_LOG_DIR=/roslog 
              && export ROSCONSOLE_CONFIG_FILE=/roslog/roslog.conf 
              && cd /catkin_ws 
              && catkin build 
              && export ROS_MASTER_URI=http://${HOST_IP}:11311 
              && roscore 
              && tail -f /dev/null"

  pub:
    build:
      context: images/ros_base
      dockerfile: Dockerfile
      target: ros_image
    network_mode: "host"
    depends_on: 
       - roscore
    volumes:
        - ${WORKSPACE_DIR}:/catkin_ws
        - ${ROS_LOG_DIR}:/roslog
    command: >
              bash -c "
              source /opt/ros/noetic/setup.bash 
              && sleep 5 
              && export ROS_LOG_DIR=/roslog 
              && export ROSCONSOLE_CONFIG_FILE=/roslog/roslog.conf 
              && export ROS_MASTER_URI=http://${HOST_IP}:11311 
              && export ROS_HOSTNAME=${PUB_IP} 
              && roslaunch pub_sub pub.launch
              && tail -f /dev/null"
  sub:
    build:
      context: images/ros_base
      dockerfile: Dockerfile
      target: ros_image
    network_mode: "host"
    depends_on: 
       - roscore
    volumes:
        - ${WORKSPACE_DIR}:/catkin_ws
        - ${ROS_LOG_DIR}:/roslog
    command: >
              bash -c "
              source /opt/ros/noetic/setup.bash 
              && sleep 5 
              && export ROS_LOG_DIR=/roslog 
              && export ROSCONSOLE_CONFIG_FILE=/roslog/roslog.conf 
              && export ROS_MASTER_URI=http://${HOST_IP}:11311 
              && export ROS_HOSTNAME=${SUB_IP} 
              && roslaunch pub_sub sub.launch
              && tail -f /dev/null"
